name = "folio-denehs"
main = "src/index.js"
compatibility_date = "2024-10-31"
compatibility_flags = ["nodejs_compat"]

# Static assets configuration
[site]
bucket = "./out"

[env.production]
name = "folio-denehs-production"
routes = [
  { pattern = "denehs.me/*", zone_name = "denehs.me" },
  { pattern = "www.denehs.me/*", zone_name = "denehs.me" }
]

# Build configuration
[build]
command = "npm run build"

# Environment variables can be set here if needed
[vars]
NODE_ENV = "production"

# Observability configuration
[observability]
enabled = true