'use client'

import { motion } from 'framer-motion'
import Image from 'next/image'

const projects = [
  {
    title: 'Future Dollar',
    description: 'A simple web app-based calculator to help people with better spending decisions.',
    process: 'Code 100% generated by Cursor + Claude 4, completed within 1 day. Gemini created the PRD, and an AI agent built the app, with light code review and manual configurations on GitHub and Cloudflare (no human coding or debugging involved).',
    liveDemo: 'https://futuredollar.denehs.me/',
    github: 'https://github.com/denehs/future-dollar',
    image: '/images/futuredollar.png'
  },
  {
    title: 'Quick Tax',
    description: 'A simplified tax software to help California tech employees calculate their estimated tax.',
    process: 'Code 100% generated by Claude Code. MVP completed within 2 days, with more enhancements added later, including a wrapped iOS app. Gemini created the PRD, and an AI agent built the app, with light code review and manual configurations on GitHub and Cloudflare (no human coding or debugging involved).',
    liveDemo: 'http://quicktax.denehs.me/',
    github: 'https://github.com/denehs/quick-tax',
    image: '/images/quicktax.png'
  }
]

export default function VibeCoding() {
  return (
    <section id="vibe-coding" className="py-20 bg-gray-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl font-bold text-center mb-12">Vibe Coding Experiments</h2>
          
          <div className="grid md:grid-cols-2 gap-8">
            {projects.map((project, index) => (
              <motion.div
                key={project.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.2 }}
                viewport={{ once: true }}
                className="bg-white rounded-lg shadow-lg overflow-hidden"
              >
                <div className="h-48 bg-gray-200 relative">
                  {/* Placeholder for project screenshot */}
                  <div className="absolute inset-0 flex items-center justify-center text-gray-500">
                    Project Screenshot
                  </div>
                </div>
                
                <div className="p-6">
                  <h3 className="text-xl font-semibold mb-2">{project.title}</h3>
                  <p className="text-gray-600 mb-4">{project.description}</p>
                  
                  <div className="mb-4">
                    <h4 className="font-semibold text-sm text-gray-700 mb-2">Development Process:</h4>
                    <p className="text-sm text-gray-600">{project.process}</p>
                  </div>
                  
                  <div className="flex space-x-4">
                    <a
                      href={project.liveDemo}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                    >
                      Live Demo →
                    </a>
                    <a
                      href={project.github}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-gray-600 hover:text-gray-800 text-sm font-medium"
                    >
                      GitHub →
                    </a>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}